# Generated by Django 5.1.3 on 2024-11-13 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=2)),
                ('description', models.TextField()),
                ('stock', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sold_by', models.CharField(default='mr_cho', max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
