# Generated by Django 5.1.3 on 2024-12-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product1_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('door_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('town_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('district_pincode', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'DataModel',
            },
        ),
    ]
